# -*- coding: utf-8 -*-
"""Temperature Monitoring System.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwYVp0AQITew872ipTnBzbGixpNFE-40
"""

import random
import time

# Accept min and max temperature limits from user
min_temp = float(input("Enter minimum temperature limit: "))
max_temp = float(input("Enter maximum temperature limit: "))

print("\nStarting Temperature Monitoring System...\n")

while True:
    # Generate random temperature (simulate IoT sensor)
    current_temp = round(random.uniform(-10, 50), 2)

    print(f"Current Temperature: {current_temp} °C")

    # Compare with limits
    if current_temp < min_temp:
        print("ALERT: Temperature is BELOW minimum limit!\n")
    elif current_temp > max_temp:
        print("ALERT: Temperature is ABOVE maximum limit!\n")
    else:
        print("Temperature is within safe range.\n")

    # Wait for 2 seconds
    time.sleep(2)